### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by Mobilpadde** [Booligoosh/carbon-tab#1]
This is pretty dang cool, so wondering when the FF add-on will be out? 😇⚡️

**Comment by Booligoosh** [comment]
Hey! I just submitted it to the Firefox Add-ons Store, so it should be out soon! 😁 
Currently number 113 in the queue to be reviewed, not sure how fast it moves.

**Comment by Booligoosh** [comment]
Hey, apologies that it didn't get on there earlier. I submitted it multiple times last year, and it was rejected all of those times (issues to do with diffs in compiled vs. source code due to environment things properly). I never managed to get it working, but I decided to try again recently, and managed to get it on there:

https://addons.mozilla.org/en-US/firefox/addon/carbon-tab/
